baseURL = 'http://effortless-frangipane-aeeddd.netlify.app/'
languageCode = 'en-us'
title = 'Client Site'
theme = 'hugo-html5up-alpha-main'

[params]
  description = "Business site for client"
  images = ["images/pic01.jpg"]
  author = "Hugo Port: [Nelson/Roberto](https://nelsonroberto.com/)"
  copyright = "© Xiao Grant. All rights reserved."
  design = "Design: [HTML5 UP](http://html5up.net/)"
  mainSections = ["blog"]

### Footer Social Media Links ###
[[params.share]]
title = "facebook"
icon = "fa-facebook-f" # fontawesome icons https://fontawesome.com/icons?d=gallery&s=brands
link = "https://www.facebook.com/"

[[params.share]]
title = "twitter"
icon = "fa-twitter"
link = "https://twitter.com/"

[[params.share]]
title = "linkedin"
icon = "fa-linkedin"
link = "https://www.linkedin.com/in/novelthinker/"


### For Pages the .RelPermalink must match the menu .URL
### For sections the name/directory must match the menu .Identifier
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 20
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 30

### Opens links in a new tab. (not working)
[markup]
  defaultMarkdownHandler = 'blackFriday'
  [markup.blackFriday]
    hrefTargetBlank = true
